name: xk6bundler
on:
  push:
    tags:
      - "v*"

jobs:
  xk6bundler:
    name: Bundle xk6 extensions
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        id: build
        uses: szkiba/xk6bundler@v0
        with:
          platform: linux/amd64 windows/amd64
          with: |
            github.com/k6io/xk6-distributed-tracing@latest
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}